<?php
if (!isset($activePage)) $activePage = '';
if (!isset($pageTitle)) $pageTitle = 'Taskify';
?>
<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo htmlspecialchars($pageTitle); ?> — Taskify</title>
<script>if(localStorage.getItem('taskify.theme')==='dark'||(!localStorage.getItem('taskify.theme')&&window.matchMedia('(prefers-color-scheme: dark)').matches)){document.documentElement.classList.add('dark')}</script>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/style.css">
</head><body><div class="app-shell">
<aside class="sidebar" id="sidebar" aria-label="Navigation"><div class="sidebar-brand"><a href="index.php" class="wordmark" aria-label="Taskify home"><span class="logo-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path stroke-linecap="round" d="m8 12 2.5 2.5L16 9"/></svg></span><span>Task<span>ify</span></span></a><button class="drawer-close" id="mobileCloseBtn" type="button" aria-label="Close navigation">×</button></div>
<nav class="sidebar-nav" aria-label="Main"><div class="nav-group"><p class="nav-label">Workspace</p>
<a href="index.php" class="nav-item <?php echo $activePage === 'dashboard' ? 'active' : ''; ?>"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg><span>Dashboard</span></a>
<a href="view-tasks.php" class="nav-item <?php echo in_array($activePage, ['view','edit','delete'], true) ? 'active' : ''; ?>"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="M9 6h11M9 12h11M9 18h11M4 6h.01M4 12h.01M4 18h.01"/></svg><span>All Tasks</span></a>
<a href="add-task.php" class="nav-item <?php echo $activePage === 'add' ? 'active' : ''; ?>"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="M12 5v14M5 12h14"/></svg><span>Add Task</span></a></div>
<div class="nav-group nav-lower"><a href="settings.php" class="nav-item <?php echo $activePage === 'settings' ? 'active' : ''; ?>"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path stroke-linecap="round" d="M19 12h2M3 12h2M12 5V3M12 21v-2M17 7l1.5-1.5M5.5 18.5 7 17M17 17l1.5 1.5M5.5 5.5 7 7"/></svg><span>Settings</span></a><a href="help.php" class="nav-item <?php echo $activePage === 'help' ? 'active' : ''; ?>"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path stroke-linecap="round" d="M9.5 9a2.6 2.6 0 1 1 4.18 2.08c-.97.73-1.68 1.19-1.68 2.42M12 17h.01"/></svg><span>Help</span></a></div></nav></aside><div class="sidebar-overlay" id="sidebarOverlay"></div>
<div class="app-main"><header class="topbar"><button class="menu-button" id="mobileMenuBtn" type="button" aria-label="Open navigation"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="M4 6h16M4 12h16M4 18h16"/></svg></button><div class="topbar-context"><p><?php echo htmlspecialchars($pageTitle); ?></p><span><?php echo date('l, j F'); ?></span></div><div class="topbar-actions"><button class="icon-button" id="themeToggle" type="button" aria-label="Switch theme"><svg id="themeIcon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg></button><a href="add-task.php" class="button button-primary button-small"><span class="plus">+</span><span>New Task</span></a><span class="avatar" title="Emmanuel">EY</span></div></header><main class="content">
